### ISSUE TITLE
Use Xdebug whitelisting

### ISSUE THREAD

**Issue by Jean85** [facile-it/paraunit#141]
PHPUnit has now a way to whitelist where to enable Xdebug, to improve performance in code coverage collection: https://thephp.cc/news/2019/01/faster-code-coverage

We could leverage this to improve Paraunit's performances. We would need to check if the feature is usable though, checking or limiting PHPUnit version and checking the Xdebug version too.

**Comment by pczerkas** [comment]
From the same article:

Update (June 22, 2021): Since this article was written, the --dump-xdebug-filter and --prepend options discussed here were [removed from PHPUnit](https://github.com/sebastianbergmann/phpunit/issues/4226#issue-617478256) because they were no longer needed thanks to [improvements in php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage/pull/747). Furthermore, most developers use the [PCOV](https://github.com/krakjoe/pcov) extensions these days to collect line coverage information and [Xdebug 3](https://xdebug.org/announcements/2020-11-25) is a lot faster than Xdebug 2.

**Comment by Jean85** [comment]
Thank you for reminding me. Closing as no longer needed.
