### ISSUE TITLE
 Lacking the --coverage-text option

### ISSUE THREAD

**Issue by alex-manno** [facile-it/paraunit#77]
For integrating Paraunit with some software would serve as the --coverage-text option of phpunit

**Comment by Jean85** [comment]
This feature seems pretty straightforward to implement, since I could use the [`SebastianBergmann\CodeCoverage\Report\Text` class](https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/Report/Text.php) straight from PHPUnit.

Ii have to test if it will work seamlessly with the Symfony process output, but it seems pretty easy.

Ping @thomasvargiu, who also was interested in this feature.
