### ISSUE TITLE
Progress in output

### ISSUE THREAD

**Issue by sergeyz** [facile-it/paraunit#91]
Hi, @Jean85, is it possible to add progress status (counters with percentage) to dots in output like PHPUnit has?

PHPUnit
```
................................................S............   61 / 1623 (  3%)
```

vs Paraunit:
```
................................................................................
```

**Comment by Jean85** [comment]
The main issue in implementing this is that Paraunit doesn't know in advance the total test count like PHPUnit, because it doesn't open/parse the tests in advance; thus, the only data that I can make available is the number of tests already completed.

But since it is a fixed number per row (80 now), it would be kind of pointless, right?

**Comment by sergeyz** [comment]
Well, counting 20+ lines becomes a mess

**Comment by Jean85** [comment]
Yeah, understandable... But still I would not have any way to know how much space I should reserve for the number, without knowing the total of the number in advance. Maybe I can say that reserving 4 chars is enough, plus space?

**Comment by sergeyz** [comment]
Let's use 5. Known cases for me are 60k and 32k unit tests

**Comment by Jean85** [comment]
Closing as done in 6e2562f
